name: Monthly Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 UTC on the 1st of every month

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set date variables
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

    - name: Install zstd/rsync
      run: sudo apt-get update && sudo apt-get install -y zstd rsync

    - name: Create a temporary directory for backup
      run: |
        mkdir -p /tmp/repo-backup
        rsync -av --exclude='.git' --exclude='.gitmodules' --exclude='.github' ./ /tmp/repo-backup/
        rm -rf *
        
    - name: Create tar.zst backup excluding .git folders
      run: |
        cd /tmp/repo-backup
        tar -I 'zstd -T0 -19' -cvf "$GITHUB_WORKSPACE/repo-backup-${{ steps.date.outputs.date }}.tar.zst" *
        
    - name: Upload backup artifact
      uses: actions/upload-artifact@v4
      with:
        name: repo-backup
        path: repo-backup-${{ steps.date.outputs.date }}.tar.zst

    - name: Check if archive > 2GB and split if needed
      id: check_size
      run: |
        file="repo-backup-${{ steps.date.outputs.date }}.tar.zst"
        max_size=$((2 * 1024 * 1024 * 1024))  # 2GB in bytes
        actual_size=$(stat -c%s "$file")
        if [ "$actual_size" -ge "$max_size" ]; then
          split -b 1996M "$file" "${file}."
          echo "split=true" >> "$GITHUB_OUTPUT"
        else
          echo "split=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Snapshot ${{ steps.date.outputs.date }}"
        tag_name: "Snapshot-${{ steps.date.outputs.date }}"
        body: |
          Automated backup for ${{ steps.date.outputs.date }}.
          Note: If archive was split due to size >2GB use cat to cat to join them together
          ```
          cat repo-backup-${{ steps.date.outputs.date }}.tar.zst.* > combined.tar.zst
          ```
        files: |
          ${{ steps.check_size.outputs.split == 'true' && format('repo-backup-{0}.tar.zst.*', steps.date.outputs.date) || format('repo-backup-{0}.tar.zst', steps.date.outputs.date) }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
