name: Monthly Submodule Update

on:
  schedule:
    - cron: '0 0 1 * *'  # At 00:00 on the 1st of every month (UTC)
  workflow_dispatch:     # Allows manual trigger

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update all submodules
        run: |
          git submodule update --init --recursive --remote --rebase

      - name: Commit and push changes
        run: |
          if git diff --quiet; then
            echo "No submodule updates."
          else
            git commit -am "chore: monthly submodule update"
            git push
          fi
